apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-eslddz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-eslddz
    app.kubernetes.io/part-of: jvm-build-suite-application-ayeu
  name: jvm-build-suite-component-eslddz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-eslddz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-eslddz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-zqpx-tenant/jvm-build-suite-application-ayeu/jvm-build-suite-component-eslddz@sha256:14ac87c0a795daa40683eb06b77480e09f9bb9266d8179dbb701dd2afb393e7f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
